apiVersion: v1
kind: Service
metadata:
  labels:
    app: mule-clusterip-service
    {{- include "labels.standard" . | nindent 4 }}
  name: mule-clusterip-service
  namespace: {{ .Release.Namespace }}
spec:
{{- if eq "false" (include "isGravity" . ) }}
  clusterIP: {{ default "" (.Values.global.service.clusterIp).muleClusteripService }}
{{- end }}
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: mule-clusterip-service
