name: first-app
deployment:
  image: quay.io/oscargcervantes/first-app
  tag: v1
  replicas: 5
  containerPort: 4043
  app_port: "4043"
  message: "Default message for first-app from helm"
  messagev1: "Default message for v1 endpoint from helm"
  messagev2: "Default message for v2 endpoint from helm"
  messagev3: "Default message for v3 endpoint from helm"
service:
  name: first-app-service
  selector: first-app
  port: 4043
  targetPort: 4043
  nodePort: 30112
ingress:
  name: first-app-ingress
  host: "first-app-ingress.apps.ocp4sdev.atl.dst.ibm.com"
  port: 4043
