apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "labels.standard" . | nindent 4 }}
    app: resource-cache
  name: resource-cache
  namespace: {{ .Release.Namespace }}
spec:
{{- if eq "false" (include "isGravity" . ) }}
  clusterIP: {{ default "" (.Values.global.service.clusterIp).resourceCache }}
{{- end }}
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8010
  selector:
    app: resource-cache
