apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cluster-status
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.rtfComponent" . | nindent 4 }}
    {{- include "labels.standard" . | nindent 4 }}
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Replace
  startingDeadlineSeconds: 150
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      labels:
        cronjob: cluster-status
{{ include "cluster-status-job-spec" . | nindent 4 }}
