apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-status
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.standard" . | nindent 4 }}
imagePullSecrets:
  - name: {{ .Values.global.image.pullSecretName }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rtf:cluster-status
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.standard" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - configmaps
      - events
    verbs:
      - list
      - get
  - apiGroups:
      - extensions
      - apps
    resources:
      - deployments
      - daemonsets
    verbs:
      - list
      - get
{{ if ne .Values.global.cluster.flavor "gravitational" }}
  - apiGroups:
      - ""
    resources:
      - services
      - serviceaccounts
    verbs:
      - get
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create
      - update
{{- end }}
  - apiGroups:
      - batch
    resources:
      - cronjobs
      - jobs
    verbs:
      - list
      - get
  - apiGroups:
      - ""
    resources:
      - pods
      - nodes
    verbs:
      - list
      - get
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - "pods/portforward"
    verbs:
      - create
  - apiGroups:
      - policy
    resourceNames:
      - rtf-restricted
    resources:
      - podsecuritypolicies
    verbs:
      - use

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-status
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.standard" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rtf:cluster-status
subjects:
  - kind: ServiceAccount
    name: cluster-status
    namespace: rtf
