# Default values for jboss-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: jboss-app
deployment:
  name: jboss-app-deployment
  replicas: 5
  image: quay.io/oscargcervantes/jboss-app:v1
  containerPort: 8080
service:
  name: jboss-app-service
  port: 8080
  targetPort: 8080
ingress:
  name: jboss-app-ingress
  host: jboss-app.apps.ocp4sdev.atl.dst.ibm.com
  path: /SampleWebApp
  port: 8080