{{ if eq "false" (include "isBYOK" . ) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sf-edge
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.standard" . | nindent 4 }}
imagePullSecrets:
  - name: {{ .Values.global.image.pullSecretName }}
{{- end }}
