{{ if eq .Values.global.cluster.flavor "gravitational" }}
apiVersion: v1
kind: Secret
metadata:
  name: registry-creds
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.standard" . | nindent 4 }}
data:
  {{ if eq .Values.global.image.provider "aws" }}
  AWS_REGION: {{ default "us-east-1" (.Values.global.pullCredentials).region | b64enc | quote }}
  AWS_ACCESS_KEY_ID: {{ default "aws-access-key" (.Values.global.pullCredentials).key | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ default "aws-secret-access-key" (.Values.global.pullCredentials).secret | b64enc | quote }}
  {{ end }}

  {{ if eq (.Values.global.image).provider "dpr" }}
  DOCKER_PRIVATE_REGISTRY_SERVER: {{ include "image.registryEndpoint" . | b64enc | quote }}
  DOCKER_PRIVATE_REGISTRY_USER: {{ .Values.global.pullCredentials.key | b64enc | quote }}
  DOCKER_PRIVATE_REGISTRY_PASSWORD: {{ .Values.global.pullCredentials.secret | b64enc | quote }}
  {{ end }}
type: Opaque
{{ end }}
