apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.deployment.image }}:{{ .Values.deployment.tag }}
          args: ["{{ .Values.deployment.app_port }}", "{{ .Values.deployment.app_message }}", "{{ .Values.deployment.app_messagev1 }}", "{{ .Values.deployment.app_messagev2 }}", "{{ .Values.deployment.app_messagev3 }}"]
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.deployment.containerPort }}
