# Default values for health-ui.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: health-ui
imagePullPolicy: Always
deployment:
  image: quay.io/oscargcervantes/health-ui-image
  tag: v1
  replicas: 5
  containerPort: 8080
configmap:
  name: health-ui-cm
secret:
  name: health-ui-secret
  value: U0VDUkVUMQo=
service:
  name: health-ui-service
  port: 8080
  targetPort: 8080