apiVersion: v1
kind: ConfigMap
metadata:
  name: backup-script
  namespace: kube-system
  labels:
    {{- include "labels.standard" . | nindent 4 }}
data:
  backup.sh: |
    {{ range .Files.Lines "assets/backup.sh" }}{{ . }}
    {{ end }}