{{- if .Values.activationData }}
#### This file would be rendered from rtfctl if its rtfctl installation.
apiVersion: v1
kind: Secret
metadata:
  name: custom-properties
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.standard" . | nindent 4 }}
    rtf.mulesoft.com/synchronized: "true"
stringData:
  HTTP_PROXY: {{ default "" .Values.http.proxy | quote }}
  HTTP_NO_PROXY: {{ default "" .Values.http.no_proxy | quote }}
  MONITORING_PROXY: {{ default "" .Values.monitoring.proxy | quote }}

{{- end }}
