{{- if not .Values.activationData }}
#### This file would be rendered from RTFD if activationData is valid it means its helm installation.
apiVersion: v1
kind: Secret
metadata:
  name: generated-properties
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.standard" . | nindent 4 }}
data:
  QUEUE_CLIENT_SSL_ENABLED: {{ default "true" ((.Values.queue).ssl).enabled | b64enc }}
  QUEUE_CLIENT_SSL_KEYSTORE: {{ default "/tmp/agent-keystore.p12" ((.Values.queue).ssl).keystorePath | b64enc }}
  QUEUE_CLIENT_SSL_TRUSTSTORE: {{ default "/opt/app/ssl/agent-truststore.p12" ((.Values.queue).ssl).truststorePath | b64enc }}
  {{- if .Values.global.ingressDomains }}
  INGRESS_DOMAINS: {{ default "" .Values.global.ingressDomains | b64enc }}
  {{- end }}
  MIN_K8S_VERSION: {{ default "1.16.0" (.Values.global.validate).minK8sVersion | b64enc }}
  QUEUE_PROVIDER: {{ default "MC" (.Values.queue).provider | b64enc }}
  QUEUE_BROKER: {{ default "" (.Values.queue).broker | b64enc }}
  QUEUE_ZONE: {{ default "" (.Values.queue).zone | b64enc }}
  QUEUE_NODEID: {{ default "" (.Values.queue).nodeId | b64enc }}
  {{- if (.Values.queue).brokerOverride }}
  QUEUE_BROKEROVERRIDE: {{ default "" (.Values.queue).brokerOverride | b64enc }}
  {{- end }}
  CERT_RENEWAL_URL: {{ default "" .Values.global.certRenewalUrl | b64enc }}
  AGENT_MASTERORGID: {{ default "" (.Values.agent).masterOrgId | b64enc }}
  AGENT_TARGETID: {{ default "" (.Values.agent).targetId | quote | b64enc }}
  MONITORING_INGESTURL: {{ default "" (.Values.global.anypointMonitoring).ingestUrl | b64enc }}
  MONITORING_INGESTURLLEGACY: {{ default "" (.Values.global.anypointMonitoring).ingestUrlLegacy | b64enc }}
  MONITORING_ORGANIZATIONID: {{ default "" (.Values.global.anypointMonitoring).organizationId | b64enc }}
  CONFIGRESOLVER_HOST: {{ default "" (.Values.global.resourceFetcher).overrideHost | b64enc }}
  RTF_REGION: {{ default "us-east-1" (.Values.global.validate).rtfRegion | b64enc }}

  {{- if eq .Values.global.cluster.flavor "gravitational" }}
  CLUSTER_INFLUX_NS: {{ default "monitoring" (.Values.global.influxdb).namespace | b64enc }}
  {{- end }}
  {{- if .Values.global.image.runtimeRegistry }}
  IMAGE_RUNTIMEREGISTRY: {{ .Values.global.image.runtimeRegistry | b64enc }}
  {{- end }}

{{- end}}
