{{- if .Values.muleLicense }}
#### This file would be rendered from rtfctl if its rtfctl installation.
apiVersion: v1
kind: Secret
metadata:
  name: rtf-muleruntime-license
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.standard" . | nindent 4 }}
    rtf.mulesoft.com/synchronized: "true"
stringData:
  "3": <?xml version="1.0" ?><property-set><property key="java.util.prefs:/com/mulesource/licm//license" type="text">{{ .Values.muleLicense }}</property></property-set>
  "4": <?xml version="1.0" ?><property-set><property key="java.util.prefs:/com/mulesoft/licm//license" type="text">{{ .Values.muleLicense }}</property></property-set>
{{- end }}
