{{ if ne .Values.global.cluster.flavor "gravitational" }}
apiVersion: scheduling.k8s.io/v1
{{- else }}
apiVersion: scheduling.k8s.io/v1beta1
{{- end }}
kind: PriorityClass
metadata:
  name: rtf-components-high-priority
  labels:
    {{- include "labels.standard" . | nindent 4 }}
value: 2000000
globalDefault: false
description: "Priority class used by rtf components."
