kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: rtf-restricted
  labels:
    {{- include "labels.standard" . | nindent 4 }}
rules:
- apiGroups:
  - policy
  resourceNames:
  - rtf-restricted
  resources:
  - podsecuritypolicies
  verbs:
  - use
