apiVersion: v1
kind: Service
metadata:
  labels:
    app: agent
  {{- include "labels.standard" . | nindent 4 }}
  name: metrics
  namespace: {{ .Release.Namespace }}
spec:
{{- if eq "false" (include "isGravity" . ) }}
  clusterIP: {{ default "" (.Values.global.service.clusterIp).metrics}}
{{- end }}
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: agent
