name: jboss-demo-app
deployment:
  name: jboss-demo-app-deployment
  replicas: 5
  image: quay.io/oscargcervantes/jboss-demo-app
  tag: v1
  containerPort: 8080
service:
  name: jboss-demo-app-service
  port: 8080
  targetPort: 8080
ingress:
  name: jboss-demo-app-ingress
  host: jboss-demo-app.apps.ocp4sdev.atl.dst.ibm.com
  path: /demoapp
