apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - env:
        - name: TEST1
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.configmap.name }}
              key: TEST1
        - name: TEST2
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.configmap.name }}
              key: TEST2
        - name: SECRET1
          valueFrom:
            secretKeyRef:
              name: {{ .Values.configmap.secret }}
              key: SECRET1
        image: {{ .Values.deployment.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        name: {{ .Values.name }}
        ports:
        - name: {{ .Values.name }}
          containerPort: {{ .Values.deployment.containerPort }}
