apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.service.name }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
  - name: "{{ .Values.service.port }}-tcp"
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.targetPort }}
