apiVersion: v1
kind: Service
metadata:
  labels:
    app: health-ui
  name: health-ui
spec:
  selector:
    app: health-ui
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
