apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.deployment.image }}:{{ .Values.deployment.tag }}
        ports:
        - containerPort: {{ .Values.deployment.containerPort }}
        livenessProbe:
          httpGet:
            path: {{ .Values.healthcheck.livenessPath }}
            port: {{ .Values.deployment.containerPort }}
          failureThreshold: 1
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: {{ .Values.healthcheck.startupPath }}
            port: {{ .Values.deployment.containerPort }}
          failureThreshold: 30
          periodSeconds: 10
